name: Deploy Angular App

on:
  push:
    branches:
      - main  # or whatever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # or the Node.js version you use

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build -- --prod

      - name: Delete old files on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            rm -rf /app/*  # be cautious with this command

      - name: SCP files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: dist/portfolio-front/
          target: /app

      - name: Execute commands on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /app
            pm2 start serve --name "my-angular-app" -- serve -s -l 3000
